import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

import styles from "../styles/Home.module.css";

export default function Home() {
  const [dataa, setDataa] = useState([]);
  const [reward, setReward] = useState("");

  const fetchData = async () => {
    setReward("");
    const res = await fetch(
      `https://www.deckofcardsapi.com/api/deck/new/draw/?count=3`
    );
    const data1 = await res.json();
    const data = data1.cards;
    console.log(data);


    //Test all 3 cards are same suit - red
    if (data[0].suit==="CLUBS" || data[0].suit==="SPADES") {
      if(data[1].suit==="CLUBS" || data[1].suit==="SPADES") {
        if(data[2].suit==="CLUBS" || data[2].suit==="SPADES") {
          setReward("All Black - $8");
        }
        }
      }

    //Test all 3 cards are same suit - red
    if (data[0].suit==="HEARTS" || data[0].suit==="DIAMONDS") {
      if(data[1].suit==="HEARTS" || data[1].suit==="DIAMONDS") {
        if(data[2].suit==="HEARTS" || data[2].suit==="DIAMONDS") {
          setReward("All Red - $8");
        }
        }
      }

    //Test to see if two cards are the same kind
    if (data[0].value===data[1].value) {
      setReward("Two of a Kind - $10");
    }
    if (data[0].value===data[2].value) {
      setReward("Two of a Kind - $10");
    }
    if (data[1].value===data[2].value) {
      setReward("Two of a Kind - $10");
    }

    //Test all 3 cards are even
    if (data[0].value==="2" || data[0].value==="4" || data[0].value==="6" || data[0].value==="8" || data[0].value==="10") {
      if(data[1].value==="2" || data[1].value==="4" || data[1].value==="6" || data[1].value==="8" || data[1].value==="10") {
        if(data[2].value==="2" || data[2].value==="4" || data[2].value==="6" || data[2].value==="8" || data[2].value==="10") {
          setReward("All Even - $20");
        }
        }
      }
    
    //Test all 3 cards are odd
    if (data[0].value==="3" || data[0].value==="5" || data[0].value==="7" || data[0].value==="9" || data[0].value==="ACE") {
      if(data[1].value==="3" || data[1].value==="5" || data[1].value==="7" || data[1].value==="9" || data[1].value==="ACE") {
        if(data[2].value==="3" || data[2].value==="5" || data[2].value==="7" || data[2].value==="9" || data[2].value==="ACE") {
          setReward("All Odd - $20");
        }
        }
      }
      
    //Test to see if all cards are the same kind
    if (data[0].value===data[1].value && data[0].value===data[2].value) {
      setReward("Three of a Kind - $150");
    }





    return setDataa(data);

    }
 

  const submitEntry = (event) => {
    event.preventDefault();
    fetchData();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center items-center">
        {dataa.map((item, i) => {
          return <img key={i} className="mt-20 my-8 mx-10 " src={item.image} alt="card" />;
        })}
      </div>

      <div className="flex justify-center">
        <button
          className="mt-10 my-8 px-5 py-1 font-semibold text-white bg-cyan-600 rounded-full "
          onClick={submitEntry}
        >
          Draw Cards
        </button>
      </div>
      <p className="text-4xl mt-10 text-cyan-600 font-bold text-center">{reward}</p>

    </div>
  );
}
